### PR TITLE
feat: add `//@deno-types` support

### LINKED ISSUE #28: Support `@deno-types`
SSIA

### PR DESCRIPTION
**Pull request by nekowinston**
Closes #28

### CODE REVIEW

**Comment by Omochice** [comment]
Thank you great PR!

I checked it work well on test.

**Comment by Omochice** [comment]
However, it appears that this branch is in conflict with #30.

I'm sorry, but is it possible for you to make the correction?

**Comment by nekowinston** [comment]
Resolved those conflicts. 🙂

**Comment by Omochice** [comment]
Thank you !

**Pull request merged**
